apiVersion: run.ai/v1
kind: RunaiJob
metadata:
  name: train # MUST BE SAME NAME of the "release" label under spec>templace>label bellow in order to get logs into the Run:AI dashboard
  labels:
    user: lan.feng # GASPAR: eg megh.shukla
spec:
  template:
    metadata:
      labels:
        #priorityClassName: "build" # Interactive Job if present, for Train Job REMOVE this line
        user: lan.feng # GASPAR: eg megh.shukla
        release: train # MUST BE SAME NAME of your pod "name" specify in the metadata above in order to get logs into the Run:AI dashboard
    spec:
      hostIPC: true
      schedulerName: runai-scheduler
      restartPolicy: Never
      securityContext:
        runAsUser: 235990 # insert uid found in people.epfl in admistrative data
        runAsGroup: 78930 # Please ask this to me incase you don't have it already.
        fsGroup: 78930 # Please ask this to me incase you don't have it already.
      containers:
        - name: any-name
          image: fenglan18009/unitraj
          workingDir: /mnt/nas3_rcp_enac_u0900_vita_scratch/vita-students/users/lfeng/MotionNet/unitraj
          command: [ "python" ]
          args:
            - "train.py"
            - "-c"
            - "autobot_server"
            - "--devices"
            - "0"
            - "1"
            - "2"
            - "3"
          # - "4"
          # - "5"
          # - "6"
          # - "7"
          env:
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wandb-secret
                  key: secret
            - name: PYTHONPATH
              value: "/mnt/nas3_rcp_enac_u0900_vita_scratch/vita-students/users/lfeng/MotionNet"
            - name: MPLCONFIGDIR
              value: "/mnt/nas3_rcp_enac_u0900_vita_scratch/vita-students/users/lfeng/.config/matplotlib"
            - name: WANDB_CACHE_DIR
              value: "/mnt/nas3_rcp_enac_u0900_vita_scratch/vita-students/users/lfeng/.config/wandb"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: WANDB_DATA_DIR
              value: "/mnt/nas3_rcp_enac_u0900_vita_scratch/vita-students/users/lfeng/.config/wandb"
          resources:
            limits:
              memory: "1024Gi"  # Limit to a maximum of 2 GiB of memory
              nvidia.com/gpu: 8 # GPU limit as specified by you
              cpu: "128"
            requests:
              memory: "400Gi"  # Request 1 GiB of memory
              cpu: "64"    # Request 500 millicores (0.5 cores)



          volumeMounts:
            - mountPath: /mnt/nas3_rcp_enac_u0900_vita_scratch
              name: scratch
            - mountPath: "/.config/wandb"
              name: wandb

      volumes:
        - name: scratch
          persistentVolumeClaim:
            claimName: runai-vita-lfeng-scratch
        - name: wandb
          emptyDir: { }
#        - name: VOLUME_NAME2
#          persistentVolumeClaim:
#            claimName: runai-pv-VOLUME2